name: 'QMsg Action'
description: 'To send notification via QMsg'
branding:
  icon: 'message-square'  
  color: 'blue'
inputs:
  qq:
    description: 'List of QQ that you want to send, seperate by `,` for multiple qq accounts'
    required: false
  groups:
    description: 'List of QQ groups that you want to send, seperate by `,` for multiple qq groups'
    required: false
  key:
    description: 'QMsg Secret Key'
    required: true
  message:
    description: 'QMsg Content'
    required: true
  ignoreFailure:
    description: 'Continue the Action if an error occurred. Pass `true` if ignore'
    required: false
    default: 'true'
outputs:
  response:
    description: 'HTTP Response Content from QMsg API'
runs:
  using: node12
  main: dist/index.js
