name: 'QMsg Action'
description: 'To send notification via QMsg'
inputs:
  qq:
    description: 'List of QQ that you want to send, seperate by `,` for multiple qq accounts'
    required: false
  groups:
    description: 'List of QQ groups that you want to send, seperate by `,` for multiple qq groups'
    required: false
  key:
    description: 'QMsg Secret Key'
    required: true
outputs:
  response:
    description: 'HTTP Response Content from QMsg API'
