name: Test

on: [push, pull_request]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Send A Notification Message
        uses: ./
        with:
          qq: ${{ secrets.QMSG_NOTIFY_QQ }}
          key: ${{ secrets.QMSG_KEY }}
          message: '${{ github.actor }} 针对 ${{ github.repository }} ${{ github.ref }} 的提交 ${{ github.sha }} (${{ github.event.head_commit.message }}) 的 ${{ github.workflow }} 任务部署完成'
